<!DOCTYPE html>
<html>
    <head>
        <title>{%block title%}{{title}}{%endblock%}</title>
        <meta name="keywords" content="{{keywords}}" />
        <meta name="description" content="{{desc}}" />
        <meta name="baidu_ssp_verify" content="85daa99eb8e0b62f718bb4047682b668">
        <meta http-equiv="pragma" content="no-cache" />
        <meta http-equiv="cache-control" content="no-cache" />
        <meta http-equiv="expires" content="0" />
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        {%block header%}
        <link rel="shortcut icon" href="/static/img/icon.png" />
        <link charset="utf-8" href="/static/style/app.css" rel="stylesheet" />
        <link href="http://cdn.bootcss.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
        <link href="http://cdn.bootcss.com/bootstrap/3.1.1/css/bootstrap-theme.css" rel="stylesheet">
        <link rel="stylesheet" href="/static/style/style.css" type="text/css">
        <!----link charset="utf-8" href="/static/style/bootstrap.min.css" rel="stylesheet" /---->
        <!--[if lt IE 9]>
        <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>    <![endif]--><!--bootstrap-->
        <script src="http://cdn.bootcss.com/jquery/2.0.3/jquery.min.js"></script>
        <script src="http://cdn.bootcss.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
        <script charset="utf-8" type="text/javascript" src="/static/js/kankan.js"></script>
        {%endblock%}
    </head>
    <body>
        <div id="wrap">
            <div class="navbar navbar-default navbar-fixed-top" role="navigation">
                <div class="container">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="http://www.btsousuo.net" title="BtSousuo.Net"><span class="glyphicon glyphicon-magnet"></span>&nbsp;&nbsp;&nbsp;&nbsp;Gope.Cn</a>
                    </div>
                    <div class="navbar-collapse collapse">
                        <ul class="nav navbar-nav">
                            <li>
                                <a href="http://www.btsousuo.net" title="BtSousuo.Net 首页"> <span class="glyphicon glyphicon-home"></span>&nbsp;首&nbsp;页</a>
                            </li>
                            <li>
                                <a href="/about.html" title="关于">
                                    <span class="glyphicon glyphicon-tags"></span>&nbsp;关&nbsp;于
                                </a>
                            </li> 
                        </ul> 
                     </div> 
                </div> 
            </div>
            {%block main%}
            {%endblock%}
        </div>
        <div id="footer">
            <div class="container">
                <p class="text-muted">
                Copyright @ 2013-2015 BtSousuo.net All rights reserved.
                <em class="f_info">
                    <b><a href="/about.html" title="免责声明">免责声明</a>
                </b></a>
            </div>
        </div>
    </body>
</html>
